// WARNING: DO NOT EDIT THIS FILE. THIS FILE IS MANAGED BY SPRING ROO.
// You may push code into the target .java compilation unit if you wish to edit any member(s).

package com.fettmedia.stagebook.domain;

import com.fettmedia.stagebook.domain.StageBookUser;
import javax.persistence.Entity;

privileged aspect StageBookUser_Roo_Jpa_Entity {
    
    declare @type: StageBookUser: @Entity;
    
}
